// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace LogMS.Db
{
    public partial class Admin
    {
        /// <summary>
        /// 資料編號
        /// </summary>
        public int Id { get; set; }
        public string Account { get; set; }
        public string Password { get; set; }
        /// <summary>
        /// 姓名
        /// </summary>
        public string Name { get; set; }
        public DateTime CreateDate { get; set; }
        /// <summary>
        /// 狀態
        /// </summary>
        public bool Enable { get; set; }
    }
}