// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace LogMS.Db
{
    public partial class AdminToMenu
    {
        /// <summary>
        /// 資料編號
        /// </summary>
        public int Id { get; set; }
        /// <summary>
        /// Admin資料編號
        /// </summary>
        public int AdminId { get; set; }
        /// <summary>
        /// Menu資料編號
        /// </summary>
        public int MenuId { get; set; }

        public virtual Admin Admin { get; set; }
        public virtual Menu Menu { get; set; }
    }
}